export type Program = {
  slug: string;
  name: string;
  shortName: string;
  subtitle?: string;
  goal: string;
  duration: string;
  level: string;
  days: string;
  locations: string;
  coaching: string;
  description: string;
  cta: string;
  image: string;
  price: string;
  priceNote: string;
  suitable: string[];
  notFor: string[];
  contents: string[];
  equipment: string[];
  weekly: string[];
  phases: { title: string; text: string }[];
  adaptations: string[];
  faqs: { q: string; a: string }[];
  filters: {
    goal: string[];
    level: string[];
    days: string[];
    location: string[];
    sport: string[];
    coaching: boolean;
  };
  hidden?: boolean;
};

export const programs: Program[] = [
  {
    slug: "standard-hybrid",
    name: "Superhuman Standard Hybrid Performance Program",
    shortName: "Standard Hybrid",
    goal: "Complete strength, endurance, speed, power, and athletic performance",
    duration: "12 weeks",
    level: "Intermediate–Advanced",
    days: "5–6 days",
    locations: "Gym + outdoor running",
    coaching: "Structured plan + coaching support",
    description:
      "The flagship Superhuman system for athletes who refuse to choose between lifting and endurance. You build a complete engine: strength, speed, power, work capacity, and mobility.",
    cta: "Build Complete Performance",
    image: "/images/omar-strength.jpg",
    price: "EGP 5,000",
    priceNote: "Placeholder price per 12 weeks until final package pricing is confirmed.",
    suitable: [
      "Intermediate and advanced trainees",
      "Hybrid athletes",
      "People who want to become strong and conditioned",
      "Athletes who will not choose between lifting and endurance",
    ],
    notFor: [
      "Complete beginners who have never trained consistently",
      "Anyone seeking a casual two-day maintenance plan",
      "Anyone unable to access basic gym equipment and a running surface",
    ],
    contents: [
      "Structured resistance training",
      "Running progression",
      "Olympic lifting",
      "Weighted calisthenics",
      "Sprint training",
      "Plyometrics",
      "Agility and change-of-direction work",
      "Metabolic conditioning",
      "Core development",
      "Mobility and recovery sessions",
      "Readiness and intensity guidelines",
      "Exercise videos",
      "Weekly progressions",
      "Performance testing",
      "Coaching support",
    ],
    equipment: [
      "Barbell and plates",
      "Dumbbells or kettlebells",
      "Pull-up bar",
      "Running route or track",
      "Optional: plyo box, sled, rings",
    ],
    weekly: [
      "2–3 strength / power sessions",
      "2–3 running or conditioning sessions",
      "1 mobility and recovery session",
      "Optional skill or testing day",
    ],
    phases: [
      { title: "Weeks 1–4 — Foundation", text: "Establish movement quality, aerobic base, and repeatable strength patterns." },
      { title: "Weeks 5–8 — Build", text: "Raise intensity, introduce speed and power, and increase hybrid work capacity." },
      { title: "Weeks 9–12 — Express", text: "Sharpen performance, test, and convert training into a stronger complete athlete." },
    ],
    adaptations: [
      "Improved strength and power output",
      "Better running economy and work capacity",
      "Higher athletic confidence and discipline",
      "More complete body composition support when paired with consistent nutrition",
    ],
    faqs: [
      { q: "Is this the main Superhuman program?", a: "Yes. Standard Hybrid is the complete 12-week performance system for intermediate and advanced trainees." },
      { q: "Can I run this while preparing for a race?", a: "Yes, if the race is compatible with hybrid loading. For HYROX-specific preparation, use HYROX 101." },
    ],
    filters: {
      goal: ["performance", "muscle", "hybrid"],
      level: ["intermediate", "advanced"],
      days: ["5", "6"],
      location: ["gym", "outdoor"],
      sport: ["hybrid", "hyrox", "running"],
      coaching: true,
    },
  },
  {
    slug: "lite-hybrid",
    name: "Superhuman Lite Hybrid Program",
    shortName: "Lite Hybrid",
    goal: "Strength, endurance, bodyweight control, mobility, and work capacity",
    duration: "12 weeks",
    level: "Beginner–Intermediate",
    days: "4–5 days",
    locations: "Gym or home + running",
    coaching: "Structured plan + coaching support",
    description:
      "A cleaner entry into the Superhuman method. You still train strength and endurance together, with calisthenics, running, core, and recovery built into a sustainable week.",
    cta: "Build",
    image: "/images/coaching-sprint.jpg",
    price: "EGP 5,000",
    priceNote: "Placeholder price per 12 weeks until final package pricing is confirmed.",
    suitable: [
      "Beginner and intermediate trainees",
      "People who want to become strong and conditioned",
      "Athletes who do not want to choose between lifting and endurance",
    ],
    notFor: [
      "Advanced athletes seeking Olympic lifting and high-volume hybrid loading",
      "Anyone looking for a sport-only swimming or HYROX race plan",
    ],
    contents: [
      "Structured resistance training",
      "Running progression",
      "Calisthenics",
      "Core development",
      "Mobility and recovery sessions",
      "Readiness and intensity guidelines",
      "Exercise videos",
      "Weekly progressions",
      "Performance testing",
      "Coaching support",
    ],
    equipment: [
      "Dumbbells or a basic gym",
      "Pull-up bar or rings",
      "Running route",
      "Mat for core and mobility",
    ],
    weekly: [
      "2 strength sessions",
      "2 running or conditioning sessions",
      "1 calisthenics or core session",
      "Mobility built into the week",
    ],
    phases: [
      { title: "Weeks 1–4 — Learn the system", text: "Build habits, technique, and a repeatable weekly rhythm." },
      { title: "Weeks 5–8 — Progressive load", text: "Increase strength and running volume without losing recovery." },
      { title: "Weeks 9–12 — Capacity", text: "Connect strength and endurance into a complete, confident athlete." },
    ],
    adaptations: [
      "Stronger foundational movement",
      "Improved aerobic fitness",
      "Better bodyweight control",
      "A clear training identity instead of random workouts",
    ],
    faqs: [
      { q: "I am new. Is Lite enough?", a: "Yes. Lite is designed for beginners and intermediates who want hybrid training with appropriate starting volumes." },
    ],
    filters: {
      goal: ["fat-loss", "performance", "hybrid"],
      level: ["beginner", "intermediate"],
      days: ["4", "5"],
      location: ["gym", "home", "outdoor"],
      sport: ["hybrid", "running"],
      coaching: true,
    },
  },
  {
    slug: "hyrox-101",
    name: "HYROX 101",
    shortName: "HYROX 101",
    subtitle: "12-Week Hybrid Performance Program",
    goal: "Prepare for your next HYROX race",
    duration: "12 weeks",
    level: "Intermediate",
    days: "5–6 days",
    locations: "Gym + HYROX stations + running",
    coaching: "24/7 online assistance where included",
    description:
      "Race-specific hybrid preparation for first-time and returning HYROX athletes. Running development, station strength, pacing, and simulations are organized into one 12-week system.",
    cta: "Prepare for Your Next HYROX",
    image: "/images/omar-coach-outdoor.jpg",
    price: "EGP 5,000",
    priceNote: "Placeholder price per 12 weeks until final package pricing is confirmed.",
    suitable: [
      "First-time HYROX competitors",
      "Intermediate athletes",
      "Athletes targeting improved race times",
      "Runners who need station strength",
      "Strength athletes who need race endurance",
    ],
    notFor: [
      "Athletes with no access to running or HYROX-style stations",
      "Beginners who have not yet built a basic strength and aerobic base",
    ],
    contents: [
      "Running development",
      "Easy aerobic sessions",
      "Threshold work",
      "Hill intervals",
      "Long runs",
      "Race-pace intervals",
      "Sled push and sled pull",
      "SkiErg",
      "Rowing",
      "Farmer’s carry",
      "Sandbag lunges",
      "Burpee broad jumps",
      "Wall balls",
      "Strength-endurance sessions",
      "Maximum-strength development",
      "HYROX conditioning",
      "Race simulations",
      "Pacing strategy",
      "Mobility and recovery",
      "Exercise demonstrations",
      "24/7 online coaching assistance, where included",
    ],
    equipment: [
      "Sled, SkiErg, rower, wall balls, sandbag, farmer handles — or close substitutions",
      "Running route or treadmill",
      "Barbell or dumbbell strength setup",
    ],
    weekly: [
      "2 quality running sessions + 1 easy aerobic session",
      "2 station / strength-endurance sessions",
      "1 race-simulation or mixed hybrid day",
      "Recovery and mobility",
    ],
    phases: [
      { title: "Weeks 1–4 — Engine and stations", text: "Build aerobic volume and learn efficient station mechanics." },
      { title: "Weeks 5–8 — Race specificity", text: "Connect running and stations under fatigue." },
      { title: "Weeks 9–12 — Sharpen", text: "Simulations, pacing, and race-week readiness." },
    ],
    adaptations: [
      "Better race-pace control",
      "Stronger station output",
      "Improved strength-endurance",
      "A clearer race strategy",
    ],
    faqs: [
      { q: "Is this only for first-time HYROX athletes?", a: "No. It is built for first-timers and intermediates targeting a better race." },
    ],
    filters: {
      goal: ["performance", "race", "hybrid"],
      level: ["intermediate", "advanced"],
      days: ["5", "6"],
      location: ["gym"],
      sport: ["hyrox", "hybrid"],
      coaching: true,
    },
  },
  {
    slug: "calisthenics-running",
    name: "Superhuman Calisthenics × Running",
    shortName: "Calisthenics × Running",
    goal: "Advanced bodyweight strength with faster running",
    duration: "12 weeks",
    level: "Intermediate–Advanced",
    days: "5–6 days",
    locations: "Calisthenics park / gym + outdoor running",
    coaching: "Structured plan + progress tracking",
    description:
      "Build strict and weighted pull-ups, dips, muscle-ups, handstand push-ups, and pistol squats while developing sprint ability and 5K / 10K performance.",
    cta: "Run Fast. Move Strong.",
    image: "/images/omar-night-fins.jpg",
    price: "EGP 5,000",
    priceNote: "Placeholder price per 12 weeks until final package pricing is confirmed.",
    suitable: [
      "Athletes who want advanced calisthenics skills",
      "Runners who need upper-body and lower-body strength",
      "Hybrid trainees who prefer bars, rings, and the road",
    ],
    notFor: [
      "Athletes who cannot perform or regress a pull-up and dip",
      "Anyone seeking Olympic lifting as the primary strength method",
    ],
    contents: [
      "Three weekly running sessions",
      "Upper-body calisthenics",
      "Lower-body strength",
      "Muscle-up development",
      "Pistol-squat development",
      "Weighted calisthenics",
      "Plyometrics",
      "Speed and agility work",
      "Conditioning circuits",
      "Core training",
      "Mobility",
      "Progress tracking",
    ],
    equipment: [
      "Pull-up bar / dip bars",
      "Weight belt or backpack",
      "Running route",
      "Optional rings and parallettes",
    ],
    weekly: [
      "3 running sessions",
      "2–3 calisthenics / strength sessions",
      "Plyometrics and core inside the week",
    ],
    phases: [
      { title: "Skill and volume", text: "Build strict strength and an aerobic running base." },
      { title: "Weighted and speed", text: "Add load to calisthenics and introduce faster running." },
      { title: "Expression", text: "Muscle-up, pistol, and running performance testing." },
    ],
    adaptations: [
      "More strict and weighted pulling and dipping strength",
      "Progress toward muscle-ups and handstand push-ups",
      "Improved 5K and 10K capacity",
      "Better sprint and jump ability",
    ],
    faqs: [
      { q: "Do I need to already have a muscle-up?", a: "No. The program develops the strength and skill path. Starting with strict pull-ups and dips is the real requirement." },
    ],
    filters: {
      goal: ["performance", "muscle", "hybrid"],
      level: ["intermediate", "advanced"],
      days: ["5", "6"],
      location: ["outdoor", "gym"],
      sport: ["running", "calisthenics"],
      coaching: false,
    },
  },
  {
    slug: "ladies-bta",
    name: "Superhuman Ladies BTA Program",
    shortName: "Ladies BTA",
    subtitle: "Butt • Thighs • Abs",
    goal: "Glutes, thighs, core, lower-body strength, confidence, and complete fitness",
    duration: "12 weeks",
    level: "Beginner–Intermediate",
    days: "4–5 days",
    locations: "Gym + optional running",
    coaching: "Technique coaching and substitutions",
    description:
      "A respectful, high-performance lower-body and complete-fitness system for women. The focus is strength, shape, and capability — never shame-based body messaging.",
    cta: "Build Your Strongest Body",
    image: "/images/omar-coach-smile.jpg",
    price: "EGP 5,000",
    priceNote: "Placeholder price per 12 weeks until final package pricing is confirmed.",
    suitable: [
      "Women seeking lower-body development and complete fitness",
      "Beginner and intermediate trainees",
      "Anyone who wants structured glute, thigh, and core training with full-body support",
    ],
    notFor: [
      "Anyone looking for extreme restriction or crash dieting",
      "Athletes who want a swimming- or HYROX-only race plan",
    ],
    contents: [
      "Glute hypertrophy",
      "Hamstring development",
      "Quadriceps development",
      "Adductor and abductor training",
      "Calf and tibialis development",
      "Core stability",
      "Dynamic abdominal work",
      "Upper-body strength and toning",
      "Beginner and intermediate options",
      "Running for aerobic fitness",
      "Plyometrics",
      "Technique coaching",
      "Exercise substitutions",
      "Weekly progressive overload",
      "Recovery guidance",
    ],
    equipment: [
      "Dumbbells, cables or bands, and a hip-thrust or bench setup",
      "Optional treadmill or outdoor running",
    ],
    weekly: [
      "3 lower-body focused sessions",
      "1 upper-body session",
      "1 aerobic or plyometric session",
      "Core across the week",
    ],
    phases: [
      { title: "Activation and pattern", text: "Learn high-quality hip, knee, and core patterns." },
      { title: "Hypertrophy", text: "Progressive overload for glutes, thighs, and trunk." },
      { title: "Performance", text: "Power, running fitness, and a stronger complete body." },
    ],
    adaptations: [
      "Stronger glutes, thighs, and core",
      "Better lower-body control and confidence",
      "Improved aerobic fitness when running is included",
      "A complete training week, not isolated isolation work",
    ],
    faqs: [
      { q: "Is this only a glute program?", a: "No. BTA develops glutes, thighs, and abs inside a complete fitness system that still trains the upper body." },
    ],
    filters: {
      goal: ["muscle", "fat-loss", "performance"],
      level: ["beginner", "intermediate"],
      days: ["4", "5"],
      location: ["gym"],
      sport: ["general"],
      coaching: true,
    },
  },
  {
    slug: "swimming-open-water",
    name: "Superhuman Swimming and Open-Water Program",
    shortName: "Swimming & Open Water",
    goal: "Pool, open-water, finswimming, distance, and race preparation",
    duration: "12 weeks",
    level: "All levels by option",
    days: "4–6 days",
    locations: "Pool and/or open water",
    coaching: "Technique and race-preparation support",
    description:
      "Built from Omar’s international finswimming and open-water background. Options include pool swimming, open water, finswimming, distance swimming, and race preparation.",
    cta: "Own the Water",
    image: "/images/omar-open-water.jpg",
    price: "EGP 5,000",
    priceNote: "Placeholder price per 12 weeks until final package pricing is confirmed.",
    suitable: [
      "Pool swimmers",
      "Open-water competitors",
      "Finswimmers",
      "Distance swimmers preparing for a race",
    ],
    notFor: [
      "Non-swimmers who have not yet completed basic water safety and stroke introduction",
      "Athletes who only want dry-land training with no swim sessions",
    ],
    contents: [
      "Technique sessions",
      "Aerobic development",
      "Threshold work",
      "Speed work",
      "Race-pace training",
      "Open-water skills",
      "Sighting",
      "Drafting",
      "Turns and starts",
      "Pacing",
      "Competition preparation",
    ],
    equipment: [
      "Pool or safe open-water venue",
      "Goggles, cap, and appropriate safety buoy for open water",
      "Optional fins for finswimming options",
    ],
    weekly: [
      "3–5 swim sessions depending on option",
      "Technique + aerobic + speed distribution",
      "Optional dry-land pairing with a swimmer S&C program",
    ],
    phases: [
      { title: "Technique and aerobic base", text: "Cleaner mechanics and sustainable volume." },
      { title: "Threshold and race pace", text: "Specific speed and endurance for the chosen event." },
      { title: "Taper and race skills", text: "Starts, turns, sighting, drafting, and competition readiness." },
    ],
    adaptations: [
      "More efficient stroke mechanics",
      "Improved aerobic and threshold capacity",
      "Better open-water skills where selected",
      "Clearer race pacing",
    ],
    faqs: [
      { q: "Can I choose pool only?", a: "Yes. Pool, open water, finswimming, distance, and race-prep options are selected during onboarding." },
    ],
    filters: {
      goal: ["performance", "race"],
      level: ["beginner", "intermediate", "advanced"],
      days: ["4", "5", "6"],
      location: ["pool", "open-water"],
      sport: ["swimming", "finswimming", "open-water"],
      coaching: true,
    },
  },
  {
    slug: "swimmer-strength",
    name: "Swimmer Strength and Conditioning",
    shortName: "Swimmer S&C",
    subtitle: "Sprint and distance options",
    goal: "Swimming-specific strength, shoulder health, core, and race preparation",
    duration: "12 weeks",
    level: "Intermediate–Advanced",
    days: "3–4 dry-land days",
    locations: "Gym + pool",
    coaching: "Sport-specific programming",
    description:
      "Dry-land strength for swimmers. Choose sprint-swimmer or distance-swimmer conditioning. The work is swimming-specific: power, core, shoulder health, and race preparation — not random bodybuilding.",
    cta: "Train for the Water",
    image: "/images/underwater.jpg",
    price: "EGP 5,000",
    priceNote: "Placeholder price per 12 weeks until final package pricing is confirmed.",
    suitable: [
      "Sprint swimmers",
      "Distance swimmers",
      "Finswimmers needing land strength",
      "Open-water athletes who need durable shoulders and a stronger engine",
    ],
    notFor: [
      "Athletes who cannot access a basic gym",
      "Swimmers currently restricted from upper-body loading by a physician",
    ],
    contents: [
      "Swimming-specific strength and conditioning",
      "Core strength",
      "Shoulder health and mobility",
      "Race preparation",
      "Sprint or distance energy-system support",
    ],
    equipment: [
      "Dumbbells, cables or bands, landmine or barbell",
      "Core setup and mobility tools",
    ],
    weekly: [
      "2–3 strength sessions",
      "1 power or race-prep session",
      "Shoulder health and mobility in every week",
    ],
    phases: [
      { title: "Tissue and pattern", text: "Shoulder integrity, core, and swim-specific strength patterns." },
      { title: "Force and capacity", text: "Raise force production or endurance support by sprinter/distance track." },
      { title: "Race transfer", text: "Power, repeatability, and competition-week support." },
    ],
    adaptations: [
      "Stronger swim-specific force",
      "More resilient shoulders and trunk",
      "Better transfer to sprint or distance racing",
    ],
    faqs: [
      { q: "Is this instead of swimming?", a: "No. It is dry-land support. Pair it with your swim program or the Superhuman swimming program." },
    ],
    filters: {
      goal: ["performance", "race"],
      level: ["intermediate", "advanced"],
      days: ["3", "4"],
      location: ["gym", "pool"],
      sport: ["swimming", "finswimming", "open-water"],
      coaching: true,
    },
  },
  {
    slug: "sport-specific",
    name: "Customized Sport-Specific Strength and Conditioning",
    shortName: "Sport-Specific S&C",
    goal: "Train for your sport, not a generic gym template",
    duration: "8–16 weeks",
    level: "Athlete-dependent",
    days: "Based on competition calendar",
    locations: "Gym + sport venue",
    coaching: "Needs analysis and periodization",
    description:
      "Individualized S&C for swimmers, runners, finswimmers, combat athletes, football players, racket-sport athletes, open-water competitors, HYROX athletes, and other competitors.",
    cta: "Train for Your Sport",
    image: "/images/pool-dive.jpg",
    price: "Custom quote",
    priceNote: "Priced after needs analysis. Placeholder until final sport-package pricing is confirmed.",
    suitable: [
      "Swimmers",
      "Runners",
      "Finswimmers",
      "Combat-sport athletes",
      "Football players",
      "Racket-sport athletes",
      "Open-water competitors",
      "HYROX athletes",
      "Other competitive athletes",
    ],
    notFor: [
      "Clients who want a fixed PDF with no sport context",
      "Anyone unwilling to complete assessment and training-history review",
    ],
    contents: [
      "Athlete needs analysis",
      "Strength assessment",
      "Movement assessment",
      "Sport-specific energy-system development",
      "Speed and power development",
      "Injury-risk reduction",
      "Mobility",
      "Periodization",
      "Competition preparation",
      "Testing and reassessment",
    ],
    equipment: ["Determined after assessment"],
    weekly: ["Designed around practice, matches, and recovery"],
    phases: [
      { title: "Assess", text: "Needs analysis, strength and movement testing." },
      { title: "Build", text: "General-to-specific strength and energy-system work." },
      { title: "Compete", text: "Peak, taper, and in-season support." },
    ],
    adaptations: [
      "More relevant strength and power for the sport",
      "Better energy-system support",
      "Clearer competition-week structure",
    ],
    faqs: [
      { q: "How is this different from Standard Hybrid?", a: "Standard Hybrid is a complete general-performance system. Sport-specific S&C is built around your event, position, and calendar." },
    ],
    filters: {
      goal: ["performance", "race"],
      level: ["intermediate", "advanced"],
      days: ["3", "4", "5"],
      location: ["gym"],
      sport: ["swimming", "running", "hyrox", "combat", "football", "other"],
      coaching: true,
    },
  },
  {
    slug: "custom",
    name: "Custom Personalized Program",
    shortName: "Custom Program",
    goal: "A plan built around your life, equipment, history, and goals",
    duration: "Built to your timeline",
    level: "All levels",
    days: "Designed to your schedule",
    locations: "Gym, home, pool, or mixed",
    coaching: "Consultation + communication + adjustments",
    description:
      "A fully individualized plan based on goals, level, schedule, equipment, training history, injuries, and performance requirements.",
    cta: "Build My Personal Plan",
    image: "/images/omar-cycling.jpg",
    price: "Custom quote",
    priceNote: "Quoted after consultation. Placeholder until final custom-plan pricing is confirmed.",
    suitable: [
      "Clients with unique schedules or equipment",
      "Athletes with injuries or limitations who have medical clearance when needed",
      "Anyone who needs a plan that is not a fixed 12-week template",
    ],
    notFor: [
      "Clients who want a ready-made program with no intake process",
    ],
    contents: [
      "Initial consultation",
      "Goal analysis",
      "Training-history review",
      "Weekly schedule design",
      "Personalized exercise selection",
      "Individual running or conditioning prescription",
      "Progression system",
      "Exercise demonstration links",
      "Modifications",
      "Progress reviews",
      "Coaching communication",
      "Program adjustments",
    ],
    equipment: ["Uses the equipment you actually have"],
    weekly: ["Designed after intake"],
    phases: [
      { title: "Consult", text: "Goals, history, limitations, and schedule." },
      { title: "Design", text: "Your week, exercises, and progression rules." },
      { title: "Adjust", text: "Reviews and changes as you adapt." },
    ],
    adaptations: [
      "A plan you can actually follow",
      "Progression that matches your recovery and life",
      "Clear communication instead of a static PDF",
    ],
    faqs: [
      { q: "Is this the same as online coaching?", a: "It can include coaching communication. Elite online coaching adds weekly check-ins, video feedback, and higher-touch adjustments." },
    ],
    filters: {
      goal: ["fat-loss", "muscle", "performance", "hybrid"],
      level: ["beginner", "intermediate", "advanced"],
      days: ["3", "4", "5", "6"],
      location: ["gym", "home", "outdoor", "pool"],
      sport: ["general", "hybrid"],
      coaching: true,
    },
  },
];

export function getProgram(slug: string) {
  return programs.find((p) => p.slug === slug);
}

export const receiveItems = [
  { title: "Program manual", text: "The full training system written in clear language." },
  { title: "Weekly training calendar", text: "Know exactly what to do each day." },
  { title: "Exercise video library", text: "Demonstration links for key movements." },
  { title: "Progress tracker", text: "Log loads, times, and sessions." },
  { title: "Readiness guide", text: "Intensity decisions based on how you arrive to train." },
  { title: "Testing system", text: "Start and end measures so progress is visible." },
  { title: "Coaching support", text: "Support level depends on the selected package." },
  { title: "Mobile access", text: "Train from your phone through the selected delivery method." },
];
